In-class exercise 1.3
UW AMATH 301 - Jakob Kotas

In [1]:
import numpy as np

In [ ]:
#Newton-Raphson code presented in video
#Finds a root of f(x)=e^x-tan(x) with initial guess x=-4

x = -4  # initial guess

for j in range(0,100):

    x = x - ( np.exp(x) - np.tan(x) )/( np.exp(x)-(1/np.cos(x))**2 )
    #display(x)

    fc = np.exp(x) - np.tan(x)

    if abs(fc) < 1e-5:
        break

print(x)
print(fc)

-3.096414598500469
2.194579281487863e-06


In [ ]:
#1

x = 0
for j in range(0,100): #Emergency brakes
  x = x-(np.exp(x)+x)/(np.exp(x)+1)
  display(x)

  fc = np.exp(x)+x

  if abs(fc) < 1e-5:
    display(j)
    break

-0.5

-0.5663110031972182

-0.5671431650348622

2

In [9]:
#2
import numpy as np
#x=3 #a
x=2 #b
#x=1 #c
#x=4 #d
#x=3.99 #e
for j in range(0,100):
  x = x-(np.sin(x)+x)/(np.cos(x)+1)
  display(x)

  fc = np.sin(x)+x

  if abs(fc) < 1e-5:
    display(j)
    break

-2.9829265454696623

247.06940432293337

-194.86730267636662

-97.19806133839923

5240.84203706246

2307.1025199019423

642.9602484991492

-603.3685560884842

-299.0592095303043

1367.0289773829252

-13229.580722223332

226082.25703563486

98746.44142049958

49252.42112203866

4564.404089056632

-80015.33939836631

-27328.51988755478

1420468.4850614814

-9813575.134788137

-4903767.971179682

-2256339.0897375876

301113161.0366035

150436119.5822473

73247488.09919083

17304410.198444664

-123876718.5396981

-56759749.79867725

316048.85306952894

-27550.298565981793

-2542.18520113844

10427.47903134158

-64737.80786759458

78192.92649067976

15806.43345894821

-14049.504684476942

-6861.592634677909

-3320.6715511598677

100814986.96875535

-26647702234.881157

5585109198.914898

-1540299815.379305

50417961680.23023

25034745776.133297

-18806773560.765804

-4810712518.151817

-2323920992.1609774

113940855.58039951

-347693081.08017474

16122057528.43714

-572855712689.7625

-286316065379.09143

111851293836.969

-285972271007.76733

-127474067295.63947

-51814735008.36542

387992599965.67377

-1208995620716.4585

133105524303071.44

17253660412757.188

-860844858672.5547

-428905307809.8281

119871212101.47711

-244673840830.58606

11446455950413.479

5541790193073.121

781643744347.2158

-201706936819.0138

184756164520.74567

57132212713.40982

24346360173.891167

12067560931.553526

-8819833504.83058

254578083351.1429

64467478630.85333

7633348746.252663

-4495660113.925539

22986930821.502335

499977782.8016777

-4902270310.966779

9179088852.190964

4163902666.9820595

2081666819.2278702

768518315.1808038

-194150007.58932233

1030932595.7724938

-3327326400.2301164

-1387186784.3979235

213817826.58670878

106375805.71326575

-53989087.85349861

-11795368.938032769

1892981.2784629334

-1670281.1263046833

14744240175.942543

5859787891.158817

-8005007494.569864

-76594934.74791145

10607727682.125711

-69116145231.07751

-34462947471.832855

In [8]:
#2e

xvec = np.arange(0,4.1,0.1)
display(xvec)
itervec = xvec*0 #same size as xvec with all zeros

for i in range(0,len(xvec)):
  x=xvec[i]
  for j in range(0,100): #nested for
    x = x-(np.sin(x)+x)/(np.cos(x)+1)

    fc = np.sin(x)+x

    if abs(fc) < 1e-5:
      itervec[i] = j #algorithm succeeds, record number of iterations
      break #break out of current level of for loop only
    itervec[i] = 100 #algorithm fails, reached max iterations

display(itervec)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. ])

array([  0.,   1.,   1.,   1.,   1.,   1.,   2.,   2.,   2.,   2.,   2.,
         2.,   2.,   2.,   3.,   3.,   3.,   4.,   6.,  87., 100.,   5.,
         6., 100.,  10.,  15., 100., 100., 100.,   4., 100.,  27., 100.,
       100., 100., 100.,   7.,   4., 100.,   4.,   5.])

In [12]:
#3

xvec = np.array([4, 3.99]) #list of all x

for j in range(0,100):
  xn = xvec[-1] #x_n = last entry in xvec
  xnmo = xvec[-2] #x_(n-1) = second-to-last entry in xvec
  fxn = np.sin(xn)+xn #f(x_n)
  fxnmo = np.sin(xnmo)+xnmo #f(x_(n-1))

  #iteration step
  xnpo = xn - (fxn*(xn-xnmo))/(fxn-fxnmo) #x_(n+1)
  xvec = np.append(xvec,xnpo)

  #break out if within tolerance
  if abs(np.sin(xnpo)+xnpo) < 1e-5:
    break

display(j) #display number of iterations taken
display(xvec) #last value in xvec is our answer

4

array([ 4.00000000e+00,  3.99000000e+00, -5.46688755e+00,  1.49690794e-01,
       -1.83509912e-01, -7.73842542e-05,  2.17500951e-07])