In-class exercise 2.0
UW AMATH 301 - Jakob Kotas

In [2]:
import numpy as np

In [3]:
#1

A = np.array([[1,2,3-1j],[4+2j,-5,-6]])
print('A =',A) #(a)
print('A^T =',A.T) #(b) transpose
print('Ā = ', np.conjugate(A)) #(c) complex conjugate
print('A^* = ', np.conjugate(A).T) #(d) adjoint

A = [[ 1.+0.j  2.+0.j  3.-1.j]
 [ 4.+2.j -5.+0.j -6.+0.j]]
A^T = [[ 1.+0.j  4.+2.j]
 [ 2.+0.j -5.+0.j]
 [ 3.-1.j -6.+0.j]]
Ā =  [[ 1.-0.j  2.-0.j  3.+1.j]
 [ 4.-2.j -5.-0.j -6.-0.j]]
A^* =  [[ 1.-0.j  4.-2.j]
 [ 2.-0.j -5.-0.j]
 [ 3.+1.j -6.-0.j]]


In [5]:
#2

#(a)
numrows = 2
numcols = 3
Z = np.zeros([numrows,numcols])
print('Z =',Z)

#(b)
N = np.ones([numrows,numcols])
print('N =',N)

#(c)
M = Z
i = 1
for r in range(0,numrows):
    for c in range(0,numcols):
        M[r,c] = i
        i = i+1
print('M =',M)

#(d)
print('M+N =',M+N)
print('N+M =',N+M)

Z = [[0. 0. 0.]
 [0. 0. 0.]]
N = [[1. 1. 1.]
 [1. 1. 1.]]
M = [[1. 2. 3.]
 [4. 5. 6.]]
M+N = [[2. 3. 4.]
 [5. 6. 7.]]
N+M = [[2. 3. 4.]
 [5. 6. 7.]]


In [12]:
#3

k = np.random.randint(2,11)
v = np.random.randint(0,6,[4,1])
R1 = np.random.randint(0,6,[4,4])
R2 = np.random.randint(0,6,[4,4])
print('k =',k) #(a)
print('v =',v)
print('R1 =',R1)
print('R2 =',R2)
print('k*R1 =',k*R1) #(b)
print('R1*v =',R1@v) #(c)
print('R1*R2 =',R1@R2) #(d)
print('R2*R1 =',R2@R1) #(e)
print('R1⊙R2 =',R1*R2) #(f)

#(g)
S1 = np.matrix(R1)
S2 = np.matrix(R2)
w = np.matrix(v)
print('S1*v =',S1*v)
print('S1*S2 =',S1*S2)
print('S2*S1 =',S2*S1)
print('S1⊙S2 =',np.multiply(S1,S2))

k = 2
v = [[3]
 [0]
 [0]
 [3]]
R1 = [[5 2 4 5]
 [5 5 4 3]
 [0 4 3 2]
 [4 3 2 5]]
R2 = [[0 1 4 5]
 [4 4 4 3]
 [5 3 5 1]
 [2 0 3 0]]
k*R1 = [[10  4  8 10]
 [10 10  8  6]
 [ 0  8  6  4]
 [ 8  6  4 10]]
R1*v = [[30]
 [24]
 [ 6]
 [27]]
R1*R2 = [[38 25 63 35]
 [46 37 69 44]
 [35 25 37 15]
 [32 22 53 31]]
R2*R1 = [[25 36 26 36]
 [52 53 50 55]
 [44 48 49 49]
 [10 16 17 16]]
R1⊙R2 = [[ 0  2 16 25]
 [20 20 16  9]
 [ 0 12 15  2]
 [ 8  0  6  0]]
S1*v = [[30]
 [24]
 [ 6]
 [27]]
S1*S2 = [[38 25 63 35]
 [46 37 69 44]
 [35 25 37 15]
 [32 22 53 31]]
S2*S1 = [[25 36 26 36]
 [52 53 50 55]
 [44 48 49 49]
 [10 16 17 16]]
S1⊙S2 = [[ 0  2 16 25]
 [20 20 16  9]
 [ 0 12 15  2]
 [ 8  0  6  0]]


In [15]:
#4

va = np.array([1,2,3])
vb = np.array([-2,4,-2])
vc = np.array([-2,-1,1])

print('va·vb =',(va.T)@vb) #(a) va and vb are orthogonal
print('va·vb =',va@vb) #np.array doesn't preserve row/column orientation
print('va·vc =',va@vc) #(b) va and vc are not orthogonal
print('va⊙vb =',va*vb) #(c)
print('|va| =',np.sqrt(va@va)) #(d)

#(e)
#ma = np.matrix(va).T #np.matrix defaults to row vector
#print('ma =',ma)
#mb = np.matrix(vb).T
#mc = np.matrix(vc).T

#print('ma·mb =', (ma.T)*mb)
#print('ma⊙mb =', np.multiply(ma,mb))
#print('ma·mb ≠', ma*mb) #dimension mismatch

va·vb = 0
va·vb = 0
va·vc = -1
va⊙vb = [-2  8 -6]
|va| = 3.7416573867739413


In [ ]:
#5

x1 = np.array([2,1,0])
x2 = np.array([1,0,-2])
x3 = np.array([0,1,4])

c1 = 1
c2 = -2
c3 = -1

print('c1x1+c2x2+c3x3 =',c1*x1+c2*x2+c3*x3) #x1,x2,x3 are linearly dependent

c1x1+c2x2+c3x3 = [0 0 0]


In [19]:
#6

i3x3 = np.eye(3)
R = np.random.randint(0,6,[3,3])
detR = np.linalg.det(R)
print('I =',i3x3)
print('R =',R)
print('IR =',i3x3@R) #(a)
print('RI =',R@i3x3)
print('det(R) =',detR) #(b)
detRlong = (R[0,0]*R[1,1]*R[2,2]+R[0,1]*R[1,2]*R[2,0]+R[0,2]*R[1,0]*R[2,1]
            -R[0,2]*R[1,1]*R[2,0]-R[0,1]*R[1,0]*R[2,2]-R[0,0]*R[1,2]*R[2,1])
print('det(R) = ',detRlong) #(c)
Rinv = np.linalg.inv(R) #(d)
print('R^(-1) =',Rinv)
print('R^(-1)R =',Rinv@R) #(e)
print('RR^(-1) =',Rinv@R)

print('M =',M)
#detM = np.linalg.det(M) #(f) determinant not defined for non-square matrices
#Minv = np.linalg.inv(M) #M is non-invertible because it is not square

S = np.array([[2,1,0],[1,0,1],[0,-2,4]]) #(g) columns of S are linearly dependent
detS = np.linalg.det(S)
#Sinv = np.linalg.inv(S) #S is non-invertible (singular) despite being square because det(S)=0
print('S =',S)
print('det(S) =',detS)

I = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
R = [[0 2 4]
 [0 4 1]
 [4 3 5]]
IR = [[0. 2. 4.]
 [0. 4. 1.]
 [4. 3. 5.]]
RI = [[0. 2. 4.]
 [0. 4. 1.]
 [4. 3. 5.]]
det(R) = -56.00000000000002
det(R) =  -56
R^(-1) = [[-0.30357143 -0.03571429  0.25      ]
 [-0.07142857  0.28571429  0.        ]
 [ 0.28571429 -0.14285714  0.        ]]
R^(-1)R = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
RR^(-1) = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
M = [[1. 2. 3.]
 [4. 5. 6.]]
S = [[ 2  1  0]
 [ 1  0  1]
 [ 0 -2  4]]
det(S) = 0.0


In [18]:
#7

A = np.array([[2]])
b = np.array([7])
x = np.linalg.inv(A)@b #don't use this in general; not computationally efficient. but ok for very small systems
print('x =',x)

x = [3.5]


In [ ]:
#8

A = np.array([[5,1,1],[0,3,4],[4,0,3]])
b = np.array([-14,25,5])
x = np.linalg.inv(A)@b #don't use this in general; not computationally efficient. but ok for very small systems
print('x =',x)

x = [-4. -1.  7.]
