In-class exercise 2.2
UW AMATH 301 - Jakob Kotas

In [1]:
import numpy as np

In [2]:
#Kutz code for Jacobi iteration
#solves [[4,-1,1],[4,-8,1],[-2,1,5]] * [[x],[y],[z]] = [[7],[-21],[15]] approximately

x = np.array([0]); y = np.array([0]); z = np.array([0])
for j in range(100):
    x = np.append( x, (7+y[j]-z[j])/4 )
    y = np.append( y, (21+4*x[j]+z[j])/8 )
    z = np.append( z, (15+2*x[j]-y[j])/5 )

    if abs(x[j+1]-x[j]) < 1e-5:
        break

print(j)
print(x[j + 1])
print(y[j + 1])
print(z[j + 1])

10
1.9999818725585938
3.999993408203125
3.0000092285156246


In [17]:
#1a

x1 = np.array([0]); x2 = np.array([0]); x3 = np.array([0])
for j in range(100):
    x1 = np.append( x1, (-14-x2[j]-x3[j])/5 )
    x2 = np.append( x2, (25-4*x3[j])/3 )
    x3 = np.append( x3, (5-4*x1[j])/3 )

    if np.linalg.norm(np.array([x1[j+1]-x1[j],x2[j+1]-x2[j],x3[j+1]-x3[j]])) < 1e-5:
        break

print('iterations =',j)
print('solution using Jacobi =')
print(x1[j + 1])
print(x2[j + 1])
print(x3[j + 1])
print('solution using np.linalg.solve =')
A = np.array([[5,1,1],[0,3,4],[4,0,3]])
b = np.array([[-14],[25],[5]])
print(np.linalg.solve(A,b))
print('det(A) =',np.linalg.det(A))

iterations = 57
solution using Jacobi =
-4.000001246355898
-1.0000031944432533
6.9999980043808
solution using np.linalg.solve =
[[-4.]
 [-1.]
 [ 7.]]
det(A) = 49.000000000000014


In [26]:
#1b

x1 = np.array([0]); x2 = np.array([0]); x3 = np.array([0])
for j in range(100):
    x1 = np.append( x1, -8-2*x2[j]-3*x3[j] )
    x2 = np.append( x2, (-19-2*x1[j]-7*x3[j])/4 )
    x3 = np.append( x3, -x1[j]-x2[j] )

    if np.linalg.norm(np.array([x1[j+1]-x1[j],x2[j+1]-x2[j],x3[j+1]-x3[j]])) < 1e-5:
        break

print('iterations =',j)
print('solution using Jacobi =') #diverges
print(x1[j + 1])
print(x2[j + 1])
print(x3[j + 1])
print('solution using np.linalg.solve =')
A = np.array([[1,2,3],[2,4,7],[1,1,1]])
b = np.array([[-8],[-19],[0]])
print(np.linalg.solve(A,b))
print('det(A) =',np.linalg.det(A))

iterations = 99
solution using Jacobi =
1.2122527818199668e+44
6.512766161625519e+43
6.774199099818321e+43
solution using np.linalg.solve =
[[ 5.]
 [-2.]
 [-3.]]
det(A) = 1.0


In [23]:
#1c

x1 = np.array([0]); x2 = np.array([0]); x3 = np.array([0])
for j in range(100):
    x1 = np.append( x1, 6-2*x2[j]-3*x3[j] )
    x2 = np.append( x2, (13-2*x1[j]-7*x3[j])/4 )
    x3 = np.append( x3, (19-3*x1[j]-6*x2[j])/10 )

    if np.linalg.norm(np.array([x1[j+1]-x1[j],x2[j+1]-x2[j],x3[j+1]-x3[j]])) < 1e-5:
        break

print('iterations =',j)
print('solution using Jacobi =') #diverges
print(x1[j + 1])
print(x2[j + 1])
print(x3[j + 1])
print('solution using np.linalg.solve =')
A = np.array([[1,2,3],[2,4,7],[3,6,10]])
b = np.array([[6],[13],[19]])
#print(np.linalg.solve(A,b)) #fails with error
print('det(A) =',np.linalg.det(A))

iterations = 99
solution using Jacobi =
-1.1175225540235982e+30
-5.87830726779293e+29
-3.46884546114077e+29
solution using np.linalg.solve =
det(A) = 0.0


In [30]:
#2

#leaving equations in the order they were given
x1 = np.array([0]); x2 = np.array([0]); x3 = np.array([0])
for j in range(100):
    x1 = np.append( x1, (-14-x2[j]-x3[j])/5 )
    x2 = np.append( x2, (25-4*x3[j])/3 )
    x3 = np.append( x3, (5-4*x1[j+1])/3 )

    if np.linalg.norm(np.array([x1[j+1]-x1[j],x2[j+1]-x2[j],x3[j+1]-x3[j]])) < 1e-5:
        break

print('iterations =',j)
print('solution using Jacobi =')
print(x1[j + 1])
print(x2[j + 1])
print(x3[j + 1])
print('solution using np.linalg.solve =')
A = np.array([[5,1,1],[0,3,4],[4,0,3]])
b = np.array([[-14],[25],[5]])
print(np.linalg.solve(A,b))
print('det(A) =',np.linalg.det(A))

iterations = 28
solution using Jacobi =
-3.9999993337640847
-0.999995210348235
6.9999991116854465
solution using np.linalg.solve =
[[-4.]
 [-1.]
 [ 7.]]
det(A) = 49.000000000000014


In [31]:
#2

#rearrange equations
x1 = np.array([0]); x2 = np.array([0]); x3 = np.array([0])
for j in range(100):
    x3 = np.append( x3, (5-4*x1[j])/3 )
    x2 = np.append( x2, (25-4*x3[j+1])/3 )
    x1 = np.append( x1, (-14-x2[j+1]-x3[j+1])/5 )

    if np.linalg.norm(np.array([x1[j+1]-x1[j],x2[j+1]-x2[j],x3[j+1]-x3[j]])) < 1e-5:
        break

print('iterations =',j)
print('solution using Jacobi =')
print(x1[j + 1])
print(x2[j + 1])
print(x3[j + 1])
print('solution using np.linalg.solve =')
A = np.array([[5,1,1],[0,3,4],[4,0,3]])
b = np.array([[-14],[25],[5]])
print(np.linalg.solve(A,b))
print('det(A) =',np.linalg.det(A))

iterations = 7
solution using Jacobi =
-3.999999984410226
-1.0000003117954748
7.000000233846606
solution using np.linalg.solve =
[[-4.]
 [-1.]
 [ 7.]]
det(A) = 49.000000000000014
