In-class exercise 2.0
UW AMATH 301 - Jakob Kotas

In [2]:
import numpy as np
from scipy.linalg import lu

In [3]:
#1

# implements Naive Gauss elimination without partial pivoting. may encounter a zero pivot, which breaks the algorithm.
def naivegauss(A,b):
    # combine A and b into an augmented matrix
    augmat = np.hstack([A,b]) #horizontal concatenation. b must be column vector

    print('forward elimination, [A|b] =\n',augmat,'\n')

    n = len(b)

    # forward elimination
    for i in range(0,n-1): #iterate over columns
        for j in range(i+1,n): #iterate over rows in this column, below the pivot
            factor = augmat[j,i]/augmat[i,i]
            augmat[j,:] = augmat[j,:] - factor*augmat[i,:]

            print('i =',i,', j=',j,', [A|b] =\n',augmat,'\n')

    # back substitution
    print('back substitution\n')
    for i in range(n-1,-1,-1): #iterate over columns
        for j in range(i-1,-1,-1): #iterate over rows in this column, above the pivot
            factor = augmat[j,i]/augmat[i,i]
            augmat[j,:] = augmat[j,:] - factor*augmat[i,:]

            print('i =',i,', j=',j,', [A|b] =\n',augmat,'\n')

    # scale diagonal elements to 1
    for i in range(0,n):
        augmat[i,:] = augmat[i,:]/augmat[i,i]

    print('final augmented matrix [A|b]=\n',augmat,'\n')
    return augmat[:,n]

In [ ]:
naivegauss([[1,1,1],[1,2,4],[1,3,9]],[[1],[-1],[1]]) #from Kutz video 2.1a

forward elimination, [A|b] =
 [[ 1  1  1  1]
 [ 1  2  4 -1]
 [ 1  3  9  1]] 

i = 0 , j= 1 , [A|b] =
 [[ 1  1  1  1]
 [ 0  1  3 -2]
 [ 1  3  9  1]] 

i = 0 , j= 2 , [A|b] =
 [[ 1  1  1  1]
 [ 0  1  3 -2]
 [ 0  2  8  0]] 

i = 1 , j= 2 , [A|b] =
 [[ 1  1  1  1]
 [ 0  1  3 -2]
 [ 0  0  2  4]] 

back substitution

i = 2 , j= 1 , [A|b] =
 [[ 1  1  1  1]
 [ 0  1  0 -8]
 [ 0  0  2  4]] 

i = 2 , j= 0 , [A|b] =
 [[ 1  1  0 -1]
 [ 0  1  0 -8]
 [ 0  0  2  4]] 

i = 1 , j= 0 , [A|b] =
 [[ 1  0  0  7]
 [ 0  1  0 -8]
 [ 0  0  2  4]] 

final augmented matrix [A|b]=
 [[ 1  0  0  7]
 [ 0  1  0 -8]
 [ 0  0  1  2]] 



array([ 7, -8,  2])

In [ ]:
naivegauss([[5,1,1],[0,3,4],[4,0,3]],[[-14],[25],[5]]) #wrong answer (!)

forward elimination, [A|b] =
 [[  5   1   1 -14]
 [  0   3   4  25]
 [  4   0   3   5]] 

i = 0 , j= 1 , [A|b] =
 [[  5   1   1 -14]
 [  0   3   4  25]
 [  4   0   3   5]] 

i = 0 , j= 2 , [A|b] =
 [[  5   1   1 -14]
 [  0   3   4  25]
 [  0   0   2  16]] 

i = 1 , j= 2 , [A|b] =
 [[  5   1   1 -14]
 [  0   3   4  25]
 [  0   0   2  16]] 

back substitution

i = 2 , j= 1 , [A|b] =
 [[  5   1   1 -14]
 [  0   3   0  -7]
 [  0   0   2  16]] 

i = 2 , j= 0 , [A|b] =
 [[  5   1   0 -22]
 [  0   3   0  -7]
 [  0   0   2  16]] 

i = 1 , j= 0 , [A|b] =
 [[  5   0   0 -19]
 [  0   3   0  -7]
 [  0   0   2  16]] 

final augmented matrix [A|b]=
 [[ 1  0  0 -3]
 [ 0  1  0 -2]
 [ 0  0  1  8]] 



array([-3, -2,  8])

In [ ]:
naivegauss([[5.,1,1],[0,3,4],[4,0,3]],[[-14],[25],[5]]) #force python to use floats, this gives the right answer

forward elimination, [A|b] =
 [[  5.   1.   1. -14.]
 [  0.   3.   4.  25.]
 [  4.   0.   3.   5.]] 

i = 0 , j= 1 , [A|b] =
 [[  5.   1.   1. -14.]
 [  0.   3.   4.  25.]
 [  4.   0.   3.   5.]] 

i = 0 , j= 2 , [A|b] =
 [[  5.    1.    1.  -14. ]
 [  0.    3.    4.   25. ]
 [  0.   -0.8   2.2  16.2]] 

i = 1 , j= 2 , [A|b] =
 [[  5.           1.           1.         -14.        ]
 [  0.           3.           4.          25.        ]
 [  0.           0.           3.26666667  22.86666667]] 

i = 2 , j= 1 , [A|b] =
 [[  5.           1.           1.         -14.        ]
 [  0.           3.           0.          -3.        ]
 [  0.           0.           3.26666667  22.86666667]] 

i = 2 , j= 0 , [A|b] =
 [[  5.           1.           0.         -21.        ]
 [  0.           3.           0.          -3.        ]
 [  0.           0.           3.26666667  22.86666667]] 

i = 1 , j= 0 , [A|b] =
 [[  5.           0.           0.         -20.        ]
 [  0.           3.           0.       

array([-4., -1.,  7.])

In [46]:
#2

A=np.array([[1,2,3],[4,5,6],[7,8,0]])
print('A =',A)

#a
L2=np.array([[1,0,0],[0,1,0],[0,-2,1]])
L2inv = np.linalg.inv(L2)
print('L2^(-1) =',L2inv)

#b
L1=np.array([[1,0,0],[-4,1,0],[-7,0,1]])
L1inv = np.linalg.inv(L1)
print('L1^(-1) =',L1inv)

#c
L=L1inv@L2inv
print('L =',L)

U=np.array([[1,2,3],[0,-3,-6],[0,0,-9]])
print('LU =',L@U) #check that LU=A


A = [[1 2 3]
 [4 5 6]
 [7 8 0]]
L2^(-1) = [[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  2.  1.]]
L1^(-1) = [[ 1. -0. -0.]
 [ 4.  1.  0.]
 [ 7.  0.  1.]]
L = [[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]
LU = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 0.]]


In [45]:
#3a

A = np.array([[1.,2,3],[2,4,7],[1,1,1]])
b = np.array([[-8],[-19],[0]])

naivegauss(A,b) #fails

forward elimination, [A|b] =
 [[  1.   2.   3.  -8.]
 [  2.   4.   7. -19.]
 [  1.   1.   1.   0.]] 

i = 0 , j= 1 , [A|b] =
 [[ 1.  2.  3. -8.]
 [ 0.  0.  1. -3.]
 [ 1.  1.  1.  0.]] 

i = 0 , j= 2 , [A|b] =
 [[ 1.  2.  3. -8.]
 [ 0.  0.  1. -3.]
 [ 0. -1. -2.  8.]] 

i = 1 , j= 2 , [A|b] =
 [[  1.   2.   3.  -8.]
 [  0.   0.   1.  -3.]
 [ nan  nan  inf -inf]] 

back substitution

i = 2 , j= 1 , [A|b] =
 [[  1.   2.   3.  -8.]
 [ nan  nan  nan  nan]
 [ nan  nan  inf -inf]] 

i = 2 , j= 0 , [A|b] =
 [[ nan  nan  nan  nan]
 [ nan  nan  nan  nan]
 [ nan  nan  inf -inf]] 

i = 1 , j= 0 , [A|b] =
 [[ nan  nan  nan  nan]
 [ nan  nan  nan  nan]
 [ nan  nan  inf -inf]] 

final augmented matrix [A|b]=
 [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]] 



<ipython-input-3-9025ec952f6f>:15: RuntimeWarning: divide by zero encountered in scalar divide
  factor = augmat[j,i]/augmat[i,i]
<ipython-input-3-9025ec952f6f>:16: RuntimeWarning: invalid value encountered in multiply
  augmat[j,:] = augmat[j,:] - factor*augmat[i,:]
<ipython-input-3-9025ec952f6f>:25: RuntimeWarning: invalid value encountered in multiply
  augmat[j,:] = augmat[j,:] - factor*augmat[i,:]
<ipython-input-3-9025ec952f6f>:31: RuntimeWarning: invalid value encountered in divide
  augmat[i,:] = augmat[i,:]/augmat[i,i]


array([nan, nan, nan])

In [15]:
x = np.array([5,-2,-3]) #check that this x does solve Ax=b

print('Ax =',A@x)
print('b =',b)

Ax = [ -8. -19.   0.]
b = [[ -8]
 [-19]
 [  0]]


In [29]:
#3b

# implements Gauss elimination with partial pivoting
def gauss(A,b):
    # combine A and b into an augmented matrix
    augmat = np.hstack([A,b]) #horizontal concatenation. b must be column vector

    print('forward elimination, [A|b] =\n',augmat,'\n')

    n = len(b)

    # forward elimination
    for i in range(0,n-1): #iterate over columns
        #partial pivoting steps below-------------------------------------------
        rowtobepivot = i+np.argmax(np.abs(augmat[i:,i]))
        print('rowtobepivot=',rowtobepivot)
        if rowtobepivot!=i: #swap rows
            augmat[[rowtobepivot,i]] = augmat[[i,rowtobepivot]]
            print('rows swapped, [A|b] =\n',augmat,'\n')
        #partial pivoting steps above-------------------------------------------

        for j in range(i+1,n): #iterate over rows in this column, below the pivot
            factor = augmat[j,i]/augmat[i,i]
            augmat[j,:] = augmat[j,:] - factor*augmat[i,:]

            print('i =',i,', j=',j,', [A|b] =\n',augmat,'\n')

    # back substitution
    print('back substitution\n')
    for i in range(n-1,-1,-1): #iterate over columns
        for j in range(i-1,-1,-1): #iterate over rows in this column, above the pivot
            factor = augmat[j,i]/augmat[i,i]
            augmat[j,:] = augmat[j,:] - factor*augmat[i,:]

            print('i =',i,', j=',j,', [A|b] =\n',augmat,'\n')

    # scale diagonal elements to 1
    for i in range(0,n):
        augmat[i,:] = augmat[i,:]/augmat[i,i]

    print('final augmented matrix [A|b]=\n',augmat,'\n')
    return augmat[:,n]

In [52]:
#3c

A = np.array([[1.,2,3],[2,4,7],[1,1,1]])
b = np.array([[-8],[-19],[0]])

gauss(A,b)

forward elimination, [A|b] =
 [[  1.   2.   3.  -8.]
 [  2.   4.   7. -19.]
 [  1.   1.   1.   0.]] 

rowtobepivot= 1
rows swapped, [A|b] =
 [[  2.   4.   7. -19.]
 [  1.   2.   3.  -8.]
 [  1.   1.   1.   0.]] 

i = 0 , j= 1 , [A|b] =
 [[  2.    4.    7.  -19. ]
 [  0.    0.   -0.5   1.5]
 [  1.    1.    1.    0. ]] 

i = 0 , j= 2 , [A|b] =
 [[  2.    4.    7.  -19. ]
 [  0.    0.   -0.5   1.5]
 [  0.   -1.   -2.5   9.5]] 

rowtobepivot= 2
rows swapped, [A|b] =
 [[  2.    4.    7.  -19. ]
 [  0.   -1.   -2.5   9.5]
 [  0.    0.   -0.5   1.5]] 

i = 1 , j= 2 , [A|b] =
 [[  2.    4.    7.  -19. ]
 [  0.   -1.   -2.5   9.5]
 [  0.    0.   -0.5   1.5]] 

back substitution

i = 2 , j= 1 , [A|b] =
 [[  2.    4.    7.  -19. ]
 [  0.   -1.    0.    2. ]
 [  0.    0.   -0.5   1.5]] 

i = 2 , j= 0 , [A|b] =
 [[ 2.   4.   0.   2. ]
 [ 0.  -1.   0.   2. ]
 [ 0.   0.  -0.5  1.5]] 

i = 1 , j= 0 , [A|b] =
 [[ 2.   0.   0.  10. ]
 [ 0.  -1.   0.   2. ]
 [ 0.   0.  -0.5  1.5]] 

final augmented matri

array([ 5., -2., -3.])

In [53]:
#3c

print(np.linalg.solve(A,b))

[[ 5.]
 [-2.]
 [-3.]]


In [62]:
#4

A = np.array([[1,2,3],[2,4,7],[3,6,10]])
b = np.array([[6],[13],[19]])
#pythonsx = np.linalg.solve(A,b) #unable to find x
#print(pythonsx)

myx = np.array([[1],[1],[1]]) #solves Ax=b
print('Ax =',A@myx)

Ax = [[ 6]
 [13]
 [19]]
