In-class exercise 5.1
UW AMATH 301 - Jakob Kotas

In [13]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fminbound

In [31]:
#1(a)

def f(x):
    return x+1/x

a = 0.5
b = 5
funceval = 0

for i in range(0,101):
    x1 = 2*a/3+b/3
    x2 = a/3+2*b/3
    print(a,x1,x2,b)

    if f(x1)<f(x2):
        b = x2
    else: #f(x1)>=f(x2), including the edge-case of equality
        a = x1
    funceval += 2
    
    if b-a<1e-6:
        break

finalvalue = (a+b)/2
print('final interval: [',a,',',b,']')
print('final value: ',finalvalue)
print('number of iterations (trisection): ',i)
print('number of function evaluations (trisection):',funceval)

0.5 2.0 3.5 5
0.5 1.5 2.5 3.5
0.5 1.1666666666666667 1.8333333333333335 2.5
0.5 0.9444444444444444 1.388888888888889 1.8333333333333335
0.5 0.7962962962962963 1.0925925925925928 1.388888888888889
0.7962962962962963 0.9938271604938272 1.1913580246913582 1.388888888888889
0.7962962962962963 0.9279835390946503 1.0596707818930042 1.1913580246913582
0.9279835390946503 1.015775034293553 1.1035665294924555 1.1913580246913582
0.9279835390946503 0.9865112025605853 1.0450388660265204 1.1035665294924555
0.9279835390946503 0.9670019814052737 1.006020423715897 1.0450388660265204
0.9670019814052737 0.9930142762790226 1.0190265711527715 1.0450388660265204
0.9670019814052737 0.9843435113211063 1.001685041236939 1.0190265711527715
0.9843435113211063 0.9959045312649948 1.0074655512088833 1.0190265711527715
0.9843435113211063 0.9920508579503653 0.9997582045796243 1.0074655512088833
0.9920508579503653 0.9971890890365379 1.0023273201227105 1.0074655512088833
0.9971890890365379 1.0006145764273198 1.00404006

In [49]:
#1(b)

def f(x):
    return x+1/x #(1)
#    return x**2+np.sin(10*x) #(4)

c = (np.sqrt(5)-1)/2
a = 0.5 #(1)
#a = -0.5 #(4)
#a = -2 #(4)
b = 5
funceval = 0

x1 = c*a+(1-c)*b
x2 = (1-c)*a+c*b
fx1 = f(x1)
fx2 = f(x2)
funceval += 2
print(a,x1,x2,b)

for i in range(1,101):
    if fx1<fx2:
        b = x2
        x2 = x1
        fx2 = fx1
        x1 = c*a+(1-c)*b
        fx1 = f(x1)
        funceval += 1
    else: #f(x1)>=f(x2), including the edge-case of equality
        a = x1
        x1 = x2
        fx1 = fx2
        x2 = (1-c)*a+c*b
        fx2 = f(x2)
        funceval +=1
    print(a,x1,x2,b)
    if b-a<1e-6:
        break

finalvalue = (a+b)/2
print('final interval: [',a,',',b,']')
print('final value: ',finalvalue)
print('number of iterations (golden section): ',i)
print('number of function evaluations (golden section):',funceval)

0.5 2.218847050625473 3.281152949374527 5
0.5 1.5623058987490537 2.218847050625473 3.281152949374527
0.5 1.1565411518764193 1.5623058987490537 2.218847050625473
0.5 0.9057647468726341 1.1565411518764193 1.5623058987490537
0.5 0.7507764050037853 0.9057647468726341 1.1565411518764193
0.7507764050037853 0.9057647468726341 1.0015528100075708 1.1565411518764193
0.9057647468726341 1.0015528100075708 1.0607530887414827 1.1565411518764193
0.9057647468726341 0.9649650256065458 1.0015528100075708 1.0607530887414827
0.9649650256065458 1.0015528100075708 1.0241653043404577 1.0607530887414827
0.9649650256065458 0.9875775199394325 1.0015528100075708 1.0241653043404577
0.9875775199394325 1.0015528100075708 1.0101900142723195 1.0241653043404577
0.9875775199394325 0.996214724204181 1.0015528100075708 1.0101900142723195
0.996214724204181 1.0015528100075708 1.0048519284689295 1.0101900142723195
0.996214724204181 0.9995138426655394 1.0015528100075708 1.0048519284689295
0.996214724204181 0.9982536915462127

In [11]:
#2

def g(x):
    return np.exp(x**2)-x

funceval = 0
xgmat = np.array([[-1,0,2],[g(-1),g(0),g(2)]])
funceval += 3
print(xgmat)

for i in range(1,101):
    x1 = xgmat[0,0]
    x2 = xgmat[0,1]
    x3 = xgmat[0,2]
    gx1 = xgmat[1,0]
    gx2 = xgmat[1,1]
    gx3 = xgmat[1,2]
    
    x0 = (gx1*(x3**2-x2**2)+gx2*(x1**2-x3**2)+gx3*(x2**2-x1**2))/(2*(gx1*(x3-x2)+gx2*(x1-x3)+gx3*(x2-x1)))
    gx0 = g(x0)
    funceval += 1
    if x0<x2:
        xgmat[:,2]=np.array([x0,gx0])
    else: #x0>=x2, including edge-case of equality
        xgmat[:,0]=np.array([x0,gx0])

    sorted_indices = np.argsort(xgmat[0,:]) #sort indices of first row (x-values)
    xgmat = xgmat[:, sorted_indices] #sort the whole matrix column by column according to first row

    print(xgmat)
    if (xgmat[0,1]-xgmat[0,0]<1e-6) or (xgmat[0,2]-xgmat[0,1]<1e-6):
        xfinal = xgmat[0,1]
        break

print('final value: ',xfinal)
print('number of iterations (successive parabola): ',i)
print('number of function evaluations (successive parabola):',funceval)

[[-1.          0.          2.        ]
 [ 3.71828183  1.         52.59815003]]
[[-1.         -0.35701961  0.        ]
 [ 3.71828183  1.49296245  1.        ]]
[[-0.35701961  0.          0.15337877]
 [ 1.49296245  1.          0.87042517]]
[[0.         0.15337877 0.47893881]
 [1.         0.87042517 0.77888411]]
[[0.15337877 0.43562539 0.47893881]
 [0.87042517 0.77334548 0.77888411]]
[[0.15337877 0.4131659  0.43562539]
 [0.87042517 0.77297614 0.77334548]]
[[0.4131659  0.41846869 0.43562539]
 [0.77297614 0.77291577 0.77334548]]
[[0.41846869 0.41932665 0.43562539]
 [0.77291577 0.77291448 0.77334548]]
[[0.41932665 0.41935955 0.43562539]
 [0.77291448 0.77291448 0.77334548]]
[[0.41935955 0.41936458 0.43562539]
 [0.77291448 0.77291448 0.77334548]]
[[0.41936458 0.41936479 0.43562539]
 [0.77291448 0.77291448 0.77334548]]
final value:  0.4193647928047566
number of iterations (successive parabola):  10
number of function evaluations (successive parabola): 13


In [23]:
#3

xopt1 = fminbound(f,0.5,5)
print(xopt1)

xopt2 = fminbound(g,-1,2)
print(xopt2)

1.0000003427093387
0.41936424688048163
